# Generated by Django 3.1.6 on 2021-02-02 18:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='custom_user',
            name='ativo',
        ),
    ]
