# Generated by Django 3.1.6 on 2021-02-02 20:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questao', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resposta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resposta', models.IntegerField()),
                ('questao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questao.questao')),
            ],
        ),
    ]
