# Generated by Django 3.1.6 on 2021-02-03 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questao', '0004_nota'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nota',
            name='questao',
        ),
        migrations.AddField(
            model_name='nota',
            name='questionario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questao.questionario'),
        ),
    ]
