# Generated by Django 3.1.6 on 2021-02-05 18:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questao', '0005_auto_20210203_0149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questao',
            name='correta',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='questaocorreta', to='questao.opcao'),
        ),
    ]
