# Generated by Django 3.1.6 on 2021-02-05 19:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questao', '0008_auto_20210205_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcao',
            name='numero',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='questao',
            name='correta',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='questaocorreta', to='questao.opcao'),
        ),
    ]
