# Generated by Django 3.1.6 on 2021-02-08 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questao', '0010_auto_20210208_1557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resposta',
            name='questao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questao.questao'),
        ),
    ]
